[package]
name = "cargo-template-cli"
version = "0.1.0"
authors = ["dylan_DPC <dylan.dpc@gmail.com>"]

[dependencies]
clap = { git = "https://github.com/kbknapp/clap-rs", branch = "v3-dev" }
clap-verbosity-flag = "0.2"
clap-log-flag = "0.1"
structopt = "0.2"